#!/bin/bash

# Certificate Pinning Test Certificate Generator
# This script generates self-signed certificates for testing certificate pinning
# DO NOT use these certificates in production

set -e

OUTPUT_DIR="./test-certificates"
mkdir -p "$OUTPUT_DIR"

echo "Generating test certificates for certificate pinning..."
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Generate RSA private key and certificate
print_info "Generating RSA 2048-bit certificate..."

openssl req -x509 -newkey rsa:2048 \
  -keyout "$OUTPUT_DIR/test-rsa-key.pem" \
  -out "$OUTPUT_DIR/test-rsa-cert.pem" \
  -days 365 \
  -nodes \
  -subj "/C=US/ST=TestState/L=TestCity/O=TestOrg/CN=test.example.com"

if [ $? -eq 0 ]; then
    print_info "RSA certificate generated successfully"
else
    print_error "Failed to generate RSA certificate"
    exit 1
fi

# Extract SPKI hash for RSA certificate
print_info "Extracting SPKI SHA-256 hash from RSA certificate..."
RSA_SPKI_HASH=$(openssl x509 -in "$OUTPUT_DIR/test-rsa-cert.pem" -pubkey -noout \
  | openssl pkey -pubin -outform der \
  | openssl dgst -sha256 -binary \
  | base64)

echo "RSA Certificate SPKI Hash: $RSA_SPKI_HASH" > "$OUTPUT_DIR/rsa-spki-hash.txt"

# Extract full certificate hash
print_info "Extracting certificate SHA-256 hash from RSA certificate..."
RSA_CERT_HASH=$(openssl x509 -in "$OUTPUT_DIR/test-rsa-cert.pem" -outform der \
  | openssl dgst -sha256 -binary \
  | base64)

echo "RSA Certificate Hash: $RSA_CERT_HASH" >> "$OUTPUT_DIR/rsa-spki-hash.txt"

# Generate a second certificate for testing rotation
print_info "Generating second certificate for rotation testing..."

openssl req -x509 -newkey rsa:2048 \
  -keyout "$OUTPUT_DIR/test-rsa-key-v2.pem" \
  -out "$OUTPUT_DIR/test-rsa-cert-v2.pem" \
  -days 365 \
  -nodes \
  -subj "/C=US/ST=TestState/L=TestCity/O=TestOrg/CN=test-v2.example.com"

# Extract SPKI hash for second certificate
print_info "Extracting SPKI SHA-256 hash from second certificate..."
RSA_V2_SPKI_HASH=$(openssl x509 -in "$OUTPUT_DIR/test-rsa-cert-v2.pem" -pubkey -noout \
  | openssl pkey -pubin -outform der \
  | openssl dgst -sha256 -binary \
  | base64)

echo "RSA Certificate V2 SPKI Hash: $RSA_V2_SPKI_HASH" > "$OUTPUT_DIR/rsa-v2-spki-hash.txt"

# Generate ECDSA certificate (alternative key type)
print_info "Generating ECDSA certificate..."

openssl req -x509 -newkey ec:<(openssl ecparam -name prime256v1) \
  -keyout "$OUTPUT_DIR/test-ecdsa-key.pem" \
  -out "$OUTPUT_DIR/test-ecdsa-cert.pem" \
  -days 365 \
  -nodes \
  -subj "/C=US/ST=TestState/L=TestCity/O=TestOrg/CN=test-ecdsa.example.com"

# Extract SPKI hash for ECDSA certificate
print_info "Extracting SPKI SHA-256 hash from ECDSA certificate..."
ECDSA_SPKI_HASH=$(openssl x509 -in "$OUTPUT_DIR/test-ecdsa-cert.pem" -pubkey -noout \
  | openssl pkey -pubin -outform der \
  | openssl dgst -sha256 -binary \
  | base64)

echo "ECDSA Certificate SPKI Hash: $ECDSA_SPKI_HASH" > "$OUTPUT_DIR/ecdsa-spki-hash.txt"

# Create Swift test file with hashes
print_info "Creating Swift test configuration file..."

cat > "$OUTPUT_DIR/CertificateHashes.swift" << 'EOF'
// Auto-generated test certificate hashes
// DO NOT use in production
// Generated by: generate-test-certificate.sh

import Foundation

#if DEBUG
struct TestCertificateHashes {
    /// RSA 2048-bit certificate SPKI hash
    static let rsaSPKIHash = """
    RSA_SPKI_HASH_PLACEHOLDER
    """.trimmingCharacters(in: .whitespacesAndNewlines)

    /// RSA certificate V2 SPKI hash (for rotation testing)
    static let rsaV2SPKIHash = """
    RSA_V2_SPKI_HASH_PLACEHOLDER
    """.trimmingCharacters(in: .whitespacesAndNewlines)

    /// ECDSA certificate SPKI hash
    static let ecdsaSPKIHash = """
    ECDSA_SPKI_HASH_PLACEHOLDER
    """.trimmingCharacters(in: .whitespacesAndNewlines)

    /// All test hashes
    static let allHashes = [
        rsaSPKIHash,
        rsaV2SPKIHash,
        ecdsaSPKIHash
    ]
}
#endif
EOF

# Replace placeholders with actual hashes
sed -i '' "s|RSA_SPKI_HASH_PLACEHOLDER|$RSA_SPKI_HASH|g" "$OUTPUT_DIR/CertificateHashes.swift"
sed -i '' "s|RSA_V2_SPKI_HASH_PLACEHOLDER|$RSA_V2_SPKI_HASH|g" "$OUTPUT_DIR/CertificateHashes.swift"
sed -i '' "s|ECDSA_SPKI_HASH_PLACEHOLDER|$ECDSA_SPKI_HASH|g" "$OUTPUT_DIR/CertificateHashes.swift"

# Create README
cat > "$OUTPUT_DIR/README.md" << 'EOF'
# Test Certificates for Certificate Pinning

## ⚠️ WARNING

These certificates are for **testing purposes only**. DO NOT use them in production.

## Files

- `test-rsa-cert.pem` - RSA 2048-bit self-signed certificate
- `test-rsa-key.pem` - RSA private key
- `test-rsa-cert-v2.pem` - Second RSA certificate (for rotation testing)
- `test-ecdsa-cert.pem` - ECDSA self-signed certificate
- `*-spki-hash.txt` - SPKI hashes for each certificate
- `CertificateHashes.swift` - Swift file with hashes for testing

## Using in Tests

```swift
import AStudioMCP

#if DEBUG
let client = MCPClient(
    baseURL: URL(string: "https://test.example.com")!,
    pinnedHashes: TestCertificateHashes.allHashes,
    hashType: .spkiSHA256,
    pinningMode: .strict
)
#endif
```

## Certificate Details

### RSA Certificate
- **Key Type**: RSA 2048-bit
- **Valid For**: 365 days
- **Common Name**: test.example.com

### ECDSA Certificate
- **Key Type**: ECDSA (P-256)
- **Valid For**: 365 days
- **Common Name**: test-ecdsa.example.com

## Extracting Hashes

To extract the SPKI hash from any certificate:

```bash
openssl x509 -in certificate.pem -pubkey -noout \
  | openssl pkey -pubin -outform der \
  | openssl dgst -sha256 -binary \
  | base64
```

## Cleanup

To remove all test certificates:

```bash
rm -rf test-certificates
```
EOF

# Print summary
echo ""
print_info "Certificate generation complete!"
echo ""
echo "Generated files in $OUTPUT_DIR:"
ls -lh "$OUTPUT_DIR"
echo ""
print_info "Certificate SPKI Hashes:"
echo "  RSA:        $RSA_SPKI_HASH"
echo "  RSA V2:     $RSA_V2_SPKI_HASH"
echo "  ECDSA:      $ECDSA_SPKI_HASH"
echo ""
print_warning "Remember: These are TEST certificates only!"
print_warning "DO NOT use them in production!"
echo ""
print_info "Next steps:"
echo "  1. Review the generated certificates in: $OUTPUT_DIR"
echo "  2. Use CertificateHashes.swift in your unit tests"
echo "  3. See ../docs/guides/TLS_CERTIFICATE_PINNING.md for usage guide"
