repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json

  - repo: local
    hooks:
      - id: biome-check-write
        name: biome check (write)
        language: system
        entry: pnpm dlx @biomejs/biome check --write --files-ignore-unknown=true
        pass_filenames: true
        types_or: [javascript, jsx, ts, tsx, json]
