classDiagram
  class worker_configuration_d_5b64e8b5 {
    +packages/cloudflare-template/worker-configuration.d.ts
  }
  class generator_test_1183c7b9 {
    +packages/tokens/tests/generator.test.ts
  }