classDiagram
  class worker_configuration_d_5b64e8b5 {
    +packages/cloudflare-template/worker-configuration.d.ts
  }
  class generator_test_1183c7b9 {
    +packages/tokens/tests/generator.test.ts
  }
  class error_ca00fccf {
    +packages/cli/src/error.ts
  }
  class error_d_a0c7a013 {
    +packages/cli/dist/error.d.ts
  }
  class types_5_f869ec4b {
    +packages/widgets/src/shared/types.ts
  }
  class theme_3cb8201e {
    +packages/ui/src/utils/theme.ts
  }
  class theme_d_1_153fb1fe {
    +packages/ui/dist/utils/theme.d.ts
  }
  class components_7b12be43 {
    +packages/cli/src/commands/components.ts
  }
  class components_d_2278c559 {
    +packages/cli/dist/commands/components.d.ts
  }
  class types_d_5_2bff71d5 {
    +platforms/mcp/node_modules/zod/v3/types.d.ts
  }
  class ZodError_d_b0b18420 {
    +platforms/mcp/node_modules/zod/v3/ZodError.d.ts
  }
  class types_d_6_cae2d148 {
    +packages/widgets/node_modules/zod/v3/types.d.ts
  }
  class ZodError_d_1_ac903f56 {
    +packages/widgets/node_modules/zod/v3/ZodError.d.ts
  }
  class index_d_34_e4b9c870 {
    +packages/widgets/node_modules/motion-utils/dist/index.d.ts
  }
  class index_d_35_585977d4 {
    +packages/widgets/node_modules/motion-dom/dist/index.d.ts
  }
  class types_d_DagZKalS_d_afb2f41e {
    +packages/widgets/node_modules/framer-motion/dist/types.d-DagZKalS.d.ts
  }
  class test_mocks_ea428a2e {
    +packages/ui/src/testing/utils/test-mocks.ts
  }
  class types_d_7_9b9681b3 {
    +packages/ui/node_modules/tailwind-merge/dist/types.d.ts
  }
  class NewComponentsShowcase_d_2bda01f1 {
    +packages/ui/dist/templates/NewComponentsShowcase/NewComponentsShowcase.d.ts
  }
  class types_d_10_e5f55cbf {
    +packages/json-render/node_modules/zod/v3/types.d.ts
  }
