flowchart LR
  User(("User"))
  tailwind_config_base_114ae127["tailwind.config.base"]
  User --> tailwind_config_base_114ae127
  generate_coverage_matrix_1bd9ebaf["generate-coverage-matrix"]
  User --> generate_coverage_matrix_1bd9ebaf
  migrate_imports_aec4410b["migrate-imports"]
  User --> migrate_imports_aec4410b
  tailwind_config_f3bfbed8["tailwind.config"]
  User --> tailwind_config_f3bfbed8
  vitest_config_1_39affbd6["vitest.config"]
  User --> vitest_config_1_39affbd6
  vite_config_2_24e3337d["vite.config"]
  User --> vite_config_2_24e3337d
  worker_configuration_d_5b64e8b5["worker-configuration.d"]
  User --> worker_configuration_d_5b64e8b5
  generator_test_1183c7b9["generator.test"]
  User --> generator_test_1183c7b9
  generator_9123dcbb["generator"]
  User --> generator_9123dcbb
  alias_map_2f9c2d35["alias-map"]
  User --> alias_map_2f9c2d35
  sync_dtcg_e75f004e["sync-dtcg"]
  User --> sync_dtcg_e75f004e
  styles_90a7578c["styles"]
  User --> styles_90a7578c
  index_1_faebc14e["index"]
  User --> index_1_faebc14e
  experimental_748be63c["experimental"]
  User --> experimental_748be63c
  dev_ef260e9a["dev"]
  User --> dev_ef260e9a
  remoteClient_11373476["remoteClient"]
  User --> remoteClient_11373476
  tailwind_config_f3bfbed8 --> tailwind_preset_e0cc07c1
  classDef userNode fill:#16a34a,color:#fff