import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

import { widgetManifest } from "./src/sdk/plugins/widget-manifest";

const __dirname = fileURLToPath(new URL(".", import.meta.url));

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    widgetManifest(), // Auto-discover widgets and generate manifest
  ],
  build: {
    // Bundle size budgets - warn at 800KB to accommodate Three.js core chunk
    chunkSizeWarningLimit: 800,
    rollupOptions: {
      // Input entries are now auto-generated by widgetManifest plugin
      // Keeping manual chunks for optimization
      output: {
        entryFileNames: "assets/[name]-[hash].js",
        chunkFileNames: "assets/[name]-[hash].js",
        assetFileNames: "assets/[name]-[hash][extname]",
        // Manual chunks to optimize bundle sizes
        manualChunks(id) {
          if (id.includes("node_modules/react/") || id.includes("node_modules/react-dom/")) {
            return "vendor-react";
          }
          if (id.includes("node_modules/framer-motion/")) {
            return "vendor-motion";
          }
          if (
            id.includes("node_modules/three-stdlib/") ||
            id.includes("node_modules/postprocessing/")
          ) {
            return "vendor-three-post";
          }
          if (id.includes("node_modules/@react-three/")) {
            return "vendor-three-react";
          }
          if (id.includes("node_modules/three/src/")) {
            const subpath = id.split("node_modules/three/src/")[1] ?? "";
            const segment = subpath.split("/")[0] || "core";
            return `vendor-three-${segment}`;
          }
          if (id.includes("node_modules/three/")) {
            return "vendor-three-core";
          }
          return undefined;
        },
      },
    },
    outDir: "dist",
    emptyOutDir: true,
  },
  resolve: {
    alias: {
      "@design-studio/runtime": resolve(__dirname, "../runtime/src"),
      "@design-studio/tokens": resolve(__dirname, "../tokens/src"),
    },
  },
});
