// Auto-generated widget manifest for Cloudflare Workers
// This file is auto-generated by the widget-manifest Vite plugin
/**
 * Manifest entries keyed by widget name, with build hash metadata.
 */
export const widgetManifest = {
  "auth-demo": {
    name: "auth-demo",
    uri: "auth-demo.1612c4c0",
    hash: "1612c4c0",
    originalPath: "src/widgets/auth/auth-demo/index.html",
  },
  "past-orders": {
    name: "past-orders",
    uri: "past-orders.98787531",
    hash: "98787531",
    originalPath: "src/widgets/auth/past-orders/index.html",
  },
  "search-spotlight": {
    name: "search-spotlight",
    uri: "search-spotlight.ddfd68bc",
    hash: "ddfd68bc",
    originalPath: "src/widgets/auth/search-spotlight/index.html",
  },
  "chat-header": {
    name: "chat-header",
    uri: "chat-header.d7ec6415",
    hash: "d7ec6415",
    originalPath: "src/widgets/chat/chat-header/index.html",
  },
  "chat-input": {
    name: "chat-input",
    uri: "chat-input.55abddaf",
    hash: "55abddaf",
    originalPath: "src/widgets/chat/chat-input/index.html",
  },
  "chat-messages": {
    name: "chat-messages",
    uri: "chat-messages.db2d39e3",
    hash: "db2d39e3",
    originalPath: "src/widgets/chat/chat-messages/index.html",
  },
  "chat-sidebar": {
    name: "chat-sidebar",
    uri: "chat-sidebar.78edca71",
    hash: "78edca71",
    originalPath: "src/widgets/chat/chat-sidebar/index.html",
  },
  "chat-template": {
    name: "chat-template",
    uri: "chat-template.4715b021",
    hash: "4715b021",
    originalPath: "src/widgets/chat/chat-template/index.html",
  },
  "chat-view": {
    name: "chat-view",
    uri: "chat-view.9ef39500",
    hash: "9ef39500",
    originalPath: "src/widgets/chat/chat-view/index.html",
  },
  "compose-view": {
    name: "compose-view",
    uri: "compose-view.5d449771",
    hash: "5d449771",
    originalPath: "src/widgets/chat/compose-view/index.html",
  },
  "shopping-cart": {
    name: "shopping-cart",
    uri: "shopping-cart.fdc41e91",
    hash: "fdc41e91",
    originalPath: "src/widgets/commerce/shopping-cart/index.html",
  },
  "dashboard-widget": {
    name: "dashboard-widget",
    uri: "dashboard-widget.c70f1cf3",
    hash: "c70f1cf3",
    originalPath: "src/widgets/dashboard/dashboard-widget/index.html",
  },
  "json-render-demo": {
    name: "json-render-demo",
    uri: "json-render-demo.3654c43d",
    hash: "3654c43d",
    originalPath: "src/widgets/demo/json-render-demo/index.html",
  },
  "kitchen-sink-lite": {
    name: "kitchen-sink-lite",
    uri: "kitchen-sink-lite.2c150d10",
    hash: "2c150d10",
    originalPath: "src/widgets/demo/kitchen-sink-lite/index.html",
  },
  "pizzaz-carousel": {
    name: "pizzaz-carousel",
    uri: "pizzaz-carousel.cfc709cf",
    hash: "cfc709cf",
    originalPath: "src/widgets/pizzaz/pizzaz-carousel/index.html",
  },
  "pizzaz-gallery": {
    name: "pizzaz-gallery",
    uri: "pizzaz-gallery.176b0822",
    hash: "176b0822",
    originalPath: "src/widgets/pizzaz/pizzaz-gallery/index.html",
  },
  "pizzaz-map": {
    name: "pizzaz-map",
    uri: "pizzaz-map.c2661336",
    hash: "c2661336",
    originalPath: "src/widgets/pizzaz/pizzaz-map/index.html",
  },
  "pizzaz-markdown": {
    name: "pizzaz-markdown",
    uri: "pizzaz-markdown.9159c817",
    hash: "9159c817",
    originalPath: "src/widgets/pizzaz/pizzaz-markdown/index.html",
  },
  "pizzaz-shop": {
    name: "pizzaz-shop",
    uri: "pizzaz-shop.ba1892c0",
    hash: "ba1892c0",
    originalPath: "src/widgets/pizzaz/pizzaz-shop/index.html",
  },
  "pizzaz-table": {
    name: "pizzaz-table",
    uri: "pizzaz-table.deaea400",
    hash: "deaea400",
    originalPath: "src/widgets/pizzaz/pizzaz-table/index.html",
  },
  "solar-system": {
    name: "solar-system",
    uri: "solar-system.c4650386",
    hash: "c4650386",
    originalPath: "src/widgets/science/solar-system/index.html",
  },
  "search-results": {
    name: "search-results",
    uri: "search-results.38f3bf97",
    hash: "38f3bf97",
    originalPath: "src/widgets/search/search-results/index.html",
  },
} as const;

/**
 * Union of widget names present in the manifest.
 */
export type WidgetName = keyof typeof widgetManifest;
