// Auto-generated widget manifest for Cloudflare Workers
// This file is auto-generated by the widget-manifest Vite plugin
/**
 * Manifest entries keyed by widget name, with build hash metadata.
 */
export const widgetManifest = {
  "auth-demo": {
    name: "auth-demo",
    uri: "auth-demo.5fa533e7",
    hash: "5fa533e7",
    originalPath: "src/widgets/auth/auth-demo/index.html",
  },
  "past-orders": {
    name: "past-orders",
    uri: "past-orders.29e88ff5",
    hash: "29e88ff5",
    originalPath: "src/widgets/auth/past-orders/index.html",
  },
  "search-spotlight": {
    name: "search-spotlight",
    uri: "search-spotlight.954f6b46",
    hash: "954f6b46",
    originalPath: "src/widgets/auth/search-spotlight/index.html",
  },
  "chat-header": {
    name: "chat-header",
    uri: "chat-header.c13ae8c4",
    hash: "c13ae8c4",
    originalPath: "src/widgets/chat/chat-header/index.html",
  },
  "chat-input": {
    name: "chat-input",
    uri: "chat-input.151bc279",
    hash: "151bc279",
    originalPath: "src/widgets/chat/chat-input/index.html",
  },
  "chat-messages": {
    name: "chat-messages",
    uri: "chat-messages.0831b825",
    hash: "0831b825",
    originalPath: "src/widgets/chat/chat-messages/index.html",
  },
  "chat-sidebar": {
    name: "chat-sidebar",
    uri: "chat-sidebar.5b74c8a7",
    hash: "5b74c8a7",
    originalPath: "src/widgets/chat/chat-sidebar/index.html",
  },
  "chat-template": {
    name: "chat-template",
    uri: "chat-template.20d828f1",
    hash: "20d828f1",
    originalPath: "src/widgets/chat/chat-template/index.html",
  },
  "chat-view": {
    name: "chat-view",
    uri: "chat-view.f44b1c7a",
    hash: "f44b1c7a",
    originalPath: "src/widgets/chat/chat-view/index.html",
  },
  "compose-view": {
    name: "compose-view",
    uri: "compose-view.db5afbdb",
    hash: "db5afbdb",
    originalPath: "src/widgets/chat/compose-view/index.html",
  },
  "shopping-cart": {
    name: "shopping-cart",
    uri: "shopping-cart.af1b7e54",
    hash: "af1b7e54",
    originalPath: "src/widgets/commerce/shopping-cart/index.html",
  },
  "dashboard-widget": {
    name: "dashboard-widget",
    uri: "dashboard-widget.02ff21eb",
    hash: "02ff21eb",
    originalPath: "src/widgets/dashboard/dashboard-widget/index.html",
  },
  "json-render-demo": {
    name: "json-render-demo",
    uri: "json-render-demo.c674f86e",
    hash: "c674f86e",
    originalPath: "src/widgets/demo/json-render-demo/index.html",
  },
  "kitchen-sink-lite": {
    name: "kitchen-sink-lite",
    uri: "kitchen-sink-lite.25809f48",
    hash: "25809f48",
    originalPath: "src/widgets/demo/kitchen-sink-lite/index.html",
  },
  "pizzaz-carousel": {
    name: "pizzaz-carousel",
    uri: "pizzaz-carousel.cf1208c2",
    hash: "cf1208c2",
    originalPath: "src/widgets/pizzaz/pizzaz-carousel/index.html",
  },
  "pizzaz-gallery": {
    name: "pizzaz-gallery",
    uri: "pizzaz-gallery.2263d38b",
    hash: "2263d38b",
    originalPath: "src/widgets/pizzaz/pizzaz-gallery/index.html",
  },
  "pizzaz-map": {
    name: "pizzaz-map",
    uri: "pizzaz-map.16c88cd2",
    hash: "16c88cd2",
    originalPath: "src/widgets/pizzaz/pizzaz-map/index.html",
  },
  "pizzaz-markdown": {
    name: "pizzaz-markdown",
    uri: "pizzaz-markdown.d18f3abe",
    hash: "d18f3abe",
    originalPath: "src/widgets/pizzaz/pizzaz-markdown/index.html",
  },
  "pizzaz-shop": {
    name: "pizzaz-shop",
    uri: "pizzaz-shop.0409e91f",
    hash: "0409e91f",
    originalPath: "src/widgets/pizzaz/pizzaz-shop/index.html",
  },
  "pizzaz-table": {
    name: "pizzaz-table",
    uri: "pizzaz-table.b0c9e28e",
    hash: "b0c9e28e",
    originalPath: "src/widgets/pizzaz/pizzaz-table/index.html",
  },
  "solar-system": {
    name: "solar-system",
    uri: "solar-system.26938ec5",
    hash: "26938ec5",
    originalPath: "src/widgets/science/solar-system/index.html",
  },
  "search-results": {
    name: "search-results",
    uri: "search-results.2c150a57",
    hash: "2c150a57",
    originalPath: "src/widgets/search/search-results/index.html",
  },
} as const;

/**
 * Union of widget names present in the manifest.
 */
export type WidgetName = keyof typeof widgetManifest;
