#!/usr/bin/env node
/**
 * a11y-summary.mjs
 *
 * Pretty-prints the aggregate a11y report generated by test-runner.ts.
 * Useful for CI step summaries and local debugging.
 *
 * Usage:
 *   node platforms/web/apps/storybook/scripts/a11y-summary.mjs [report-path]
 *
 * Defaults to:  platforms/web/apps/storybook/reports/a11y-report.json
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const defaultReport = path.resolve(__dirname, "../reports/a11y-report.json");
const reportPath = process.argv[2] ?? defaultReport;

if (!fs.existsSync(reportPath)) {
  console.error(`No a11y report found at ${reportPath}`);
  console.error("Run pnpm storybook:test first to generate the report.");
  process.exit(1);
}

const report = JSON.parse(fs.readFileSync(reportPath, "utf-8"));
const { summary, stories, timestamp } = report;

const bar = (pct) => {
  const filled = Math.round(pct / 5);
  return `[${"█".repeat(filled)}${"░".repeat(20 - filled)}] ${pct}%`;
};

console.log("\n━━━ Accessibility Report ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n");
console.log(`  Generated : ${new Date(timestamp).toLocaleString()}`);
console.log(`  Stories   : ${summary.total}`);
console.log(`  Passing   : ${summary.passing}  ✅`);
console.log(`  Failing   : ${summary.failing}  ❌`);
console.log(`  Pass rate : ${bar(summary.passRate)}`);
console.log();

const failing = stories.filter((s) => s.status === "fail");
if (failing.length > 0) {
  console.log(`  ❌ Failing stories (${failing.length}):`);
  for (const s of failing) {
    console.log(`     ${s.story}  (${s.violations} violation${s.violations !== 1 ? "s" : ""})`);
  }
  console.log();
}

console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n");

// Write GitHub Actions step summary if running in CI
if (process.env.GITHUB_STEP_SUMMARY) {
  const rows = failing.map((s) => `| ❌ | ${s.story} | ${s.violations} |`).join("\n");

  const md = [
    "## ♿ Accessibility Report",
    "",
    `| | |`,
    `|---|---|`,
    `| **Stories tested** | ${summary.total} |`,
    `| **Passing** | ${summary.passing} |`,
    `| **Failing** | ${summary.failing} |`,
    `| **Pass rate** | ${summary.passRate}% |`,
    "",
    failing.length > 0
      ? `### Failing Stories\n| Status | Story | Violations |\n|---|---|---|\n${rows}`
      : "### ✅ All stories pass accessibility checks",
  ].join("\n");

  fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, `${md}\n`);
  console.log("Step summary written to GITHUB_STEP_SUMMARY.");
}
